Name:           ros-indigo-imu-filter-madgwick
Version:        1.0.15
Release:        0%{?dist}
Summary:        ROS imu_filter_madgwick package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/imu_filter_madgwick
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-dynamic-reconfigure
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-message-filters
Requires:       ros-indigo-nodelet
Requires:       ros-indigo-pluginlib
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-tf2
Requires:       ros-indigo-tf2-geometry-msgs
Requires:       ros-indigo-tf2-ros
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-dynamic-reconfigure
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-message-filters
BuildRequires:  ros-indigo-nodelet
BuildRequires:  ros-indigo-pluginlib
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-rosunit
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-tf2
BuildRequires:  ros-indigo-tf2-geometry-msgs
BuildRequires:  ros-indigo-tf2-ros

%description
Filter which fuses angular velocities, accelerations, and (optionally) magnetic
readings from a generic IMU device into an orientation. Based on code by
Sebastian Madgwick,
http://www.x-io.co.uk/node/8#open_source_ahrs_and_imu_algorithms.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon May 22 2017 Martin Günther <martin.guenther1980@gmail.com> - 1.0.15-0
- Autogenerated by Bloom

* Fri Mar 10 2017 Martin Günther <martin.guenther1980@gmail.com> - 1.0.14-0
- Autogenerated by Bloom

* Wed Sep 07 2016 Martin Günther <martin.guenther1980@gmail.com> - 1.0.13-0
- Autogenerated by Bloom

* Wed Sep 07 2016 Martin Günther <martin.guenther1980@gmail.com> - 1.0.12-1
- Autogenerated by Bloom

* Wed Sep 07 2016 Martin Günther <martin.guenther1980@gmail.com> - 1.0.12-0
- Autogenerated by Bloom

* Fri Apr 22 2016 Martin Günther <martin.guenther1980@gmail.com> - 1.0.10-0
- Autogenerated by Bloom

* Fri Oct 16 2015 Martin Günther <martin.guenther1980@gmail.com> - 1.0.9-0
- Autogenerated by Bloom

* Wed Oct 07 2015 Martin Günther <martin.guenther1980@gmail.com> - 1.0.8-0
- Autogenerated by Bloom

* Tue Oct 06 2015 Martin Günther <martin.guenther1980@gmail.com> - 1.0.6-0
- Autogenerated by Bloom

* Wed Jun 24 2015 Martin Günther <martin.guenther1980@gmail.com> - 1.0.5-0
- Autogenerated by Bloom

* Wed May 06 2015 Martin Günther <martin.guenther1980@gmail.com> - 1.0.4-0
- Autogenerated by Bloom

* Thu Jan 29 2015 Martin Günther <martin.guenther1980@gmail.com> - 1.0.3-0
- Autogenerated by Bloom

* Tue Jan 27 2015 Martin Günther <martin.guenther1980@gmail.com> - 1.0.2-0
- Autogenerated by Bloom

